---
namespace: trippsc2
name: postgresql
version: 1.0.6
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains roles for installing and configuring PostgreSQL on Linux machines.

license_file: 'LICENSE'

tags: []

dependencies:
  ansible.posix: '>=1.0.0'
  community.general: '>=1.0.0'
  community.hashi_vault: '>=6.2.0'
  community.postgresql: '>=1.0.0'
  trippsc2.hashi_vault: '>=1.3.0'

repository: https://github.com/trippsc2/ansible-collection-postgresql.git

manifest:
  directives:
    - recursive-include roles/* *.md
    - recursive-include roles/*/files **
    - exclude galaxy.yml galaxy.yaml MANIFEST.json FILES.json *.tar.gz
    - recursive-exclude tests/output **
    - recursive-exclude roles/*/molecule **
    - recursive-exclude molecule **
    - global-exclude /.* /__pycache__
