---
namespace: trippsc2
name: postgresql
version: 1.0.0
readme: README.md
authors:
  - Jim Tarpley
description: This collection contains roles for installing and configuring PostgreSQL on Linux machines.

license_file: 'LICENSE'

tags: []

dependencies: {}

repository: https://github.com/trippsc2/ansible-collection-postgresql.git

build_ignore:
  - .gitignore
