---
- name: Verify
  hosts:
    - subjects
  tasks:
    - name: Check if PostgreSQL is installed
      become: true
      check_mode: true
      ansible.builtin.dnf:
        name:
          - postgresql16-server
        state: present
      register: _package_installed

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _package_installed.changed
        fail_msg: PostgreSQL not installed
        success_msg: PostgreSQL installed

    - name: Check if PostgreSQL service is enabled
      become: true
      check_mode: true
      ansible.builtin.systemd_service:
        name: postgresql-16.service
        enabled: true
      register: _service_enabled

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _service_enabled.changed
        fail_msg: PostgreSQL service not enabled
        success_msg: PostgreSQL service enabled

    - name: Check if PostgreSQL service is running
      become: true
      check_mode: true
      ansible.builtin.systemd_service:
        name: postgresql-16.service
        state: started
      register: _service_running

    - name: Assert
      ansible.builtin.assert:
        that:
          - not _service_running.changed
        fail_msg: PostgreSQL service not running
        success_msg: PostgreSQL service running
