---
galaxy_info:
    author: Jim Tarpley
    namespace: trippsc2
    role_name: install
    description: This role installs and does initial configuration for PostgreSQL on Linux machines.
    license: MIT

    min_ansible_version: '2.14'

    platforms:
      - name: Debian
        versions:
          - bullseye
          - bookworm
      - name: EL
        versions:
          - '8'
          - '9'
      - name: Ubuntu
        versions:
          - focal
          - jammy
          - noble

collections:
  - ansible.posix
  - community.general
  - community.hashi_vault
  - community.postgresql
  - trippsc2.hashi_vault

dependencies: []
