---
_pgsql_supported_os_major_versions:
  - '8'
  - '9'

_pgsql_default_firewall_type: firewalld

_pgsql_base_directory: /var/lib/pgsql
_pgsql_data_directory: "{{ _pgsql_base_directory }}/{{ pgsql_major_version | string }}/data"
_pgsql_service_name: "postgresql-{{ pgsql_major_version | string }}.service"
_pgsql_initdb_path: "/usr/pgsql-{{ pgsql_major_version | string }}/bin/initdb"
_pgsql_conf_directory: "{{ _pgsql_data_directory }}"
