---
- name: Configure PostgreSQL
  become: true
  ansible.builtin.template:
    src: postgresql.conf.j2
    dest: "{{ _pgsql_conf_directory }}/postgresql.conf"
    owner: postgres
    group: postgres
    mode: '0600'
  notify:
    - _pgsql_restart_postgresql

- name: Configure logrotate for PostgreSQL
  when:
    - pgsql_configure_logrotate
  become: true
  ansible.builtin.template:
    src: postgres.logrotate.j2
    dest: /etc/logrotate.d/postgres
    owner: root
    group: root
    mode: '0644'

- name: Configure host-based authentication
  become: true
  ansible.builtin.template:
    src: pg_hba.conf.j2
    dest: "{{ _pgsql_conf_directory }}/pg_hba.conf"
    owner: postgres
    group: postgres
    mode: '0600'
  notify:
    - _pgsql_restart_postgresql

- name: Enable PostgreSQL service
  become: true
  ansible.builtin.systemd_service:
    name: "{{ _pgsql_service_name }}"
    enabled: true

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Start PostgreSQL service
  become: true
  ansible.builtin.systemd_service:
    name: "{{ _pgsql_service_name }}"
    state: started
