---
- name: Create PostgreSQL databases
  loop: "{{ pgsql_databases }}"
  become: true
  become_user: postgres
  community.postgresql.postgresql_db:
    name: "{{ item.name }}"
    lc_collate: "{{ item.lc_collate | default('en_US.UTF-8') }}"
    lc_ctype: "{{ item.lc_ctype | default('en_US.UTF-8') }}"
    encoding: "{{ item.encoding | default('UTF-8') }}"
    template: "{{ item.template | default('template0') }}"
    owner: postgres
    state: "{{ item.state | default('present') }}"
  vars:
    ansible_ssh_pipelining: true
