---
- name: Validate
  ansible.builtin.import_tasks: validate.yml

- name: Install
  ansible.builtin.include_tasks: "install/{{ ansible_os_family }}.yml"

- name: Initialize
  ansible.builtin.import_tasks: initialize.yml

- name: Configure
  ansible.builtin.import_tasks: configure.yml

- name: Configure firewalld
  when:
    - pgsql_configure_firewall
    - _pgsql_firewall_type == 'firewalld'
  ansible.builtin.include_tasks: firewalld.yml

- name: Configure ufw
  when:
    - pgsql_configure_firewall
    - _pgsql_firewall_type == 'ufw'
  ansible.builtin.include_tasks: ufw.yml

- name: Configure monitoring user
  when:
    - pgsql_configure_monitoring
  ansible.builtin.include_tasks: monitoring.yml

- name: Create Hashicorp Vault connection
  when:
    - pgsql_configure_vault_database_connection
  ansible.builtin.include_tasks: vault/connection.yml
